#pragma once

#define HOOK_CTOR(x, y) (x *(*)(x*))((intptr_t)GetModuleHandle(NULL) + y);

namespace GTA
{
	enum
	{
		CTaskHandsUp = 0,
		CTaskClimbLadder = 1,
		CTaskCombatRoll = 3,
		CTaskAimGunOnFoot = 4,
		CTaskMovePlayer = 5,
		CTaskPlayerOnFoot = 6,
		CTaskWeapon = 8,
		CTaskPlayerWeapon = 9,
		CTaskPlayerIdles = 10,
		CTaskFSMClone = 12,
		CTaskComplex = 12,
		CTaskAimGun = 12,
		CTaskDoNothing = 15,
		CTaskGetUp = 16,
		CTaskGetUpAndStandStill = 17,
		CTaskFallOver = 18,
		CTaskFallAndGetUp = 19,
		CTaskCrawl = 20,
		CTaskComplexOnFire = 25,
		CTaskDamageElectric = 26,
		CTaskClearLookAt = 29,
		CTaskMoveStandStill = 34,
		CTaskComplexControlMovement = 35,
		CTaskAmbientClips = 38,
		CTaskMoveInAir = 39,
		CTaskExitVehicle = 44,
		CTaskForceMotionState = 45,
		CTaskGoToAndClimbLadder = 47,
		CTaskClimbLadderFully = 48,
		CTaskVault = 50,
		CTaskDropDown = 51,
		CTaskAffectSecondaryBehaviour = 52,
		CTaskAmbientLookAtEvent = 53,
		CTaskOpenDoor = 54,
		CTaskShovePed = 55,
		CTaskSwapWeapon = 56,
		CTaskGeneralSweep = 57,
		CTaskArrestPed = 62,
		CTaskArrestPed2 = 63,
		CTaskBusted = 64,
		CTaskFirePatrol = 65,
		CTaskAmbulancePatrol = 68,
		CTaskWitness = 76,
		CTaskArmy = 78,
		CTaskCarReactToVehicleCollision = 93,
		CTaskCarReactToVehicleCollisionGetOut = 95,
		CTaskDyingDead = 97,
		CTaskChatScenario = 104,
		CTaskCowerScenario = 106,
		CTaskDeadBodyScenario = 107,
		CTaskCoupleScenario = 117,
		CTaskCower = 126,
		CTaskCrouch = 127,
		CTaskMelee = 128,
		CTaskMoveMeleeMovement = 129,
		CTaskMeleeActionResult = 130,
		CTaskComplexEvasiveStep = 137,
		CTaskComplexStuckInAir = 140,
		CTaskDuckAndCover = 146,
		CTaskAggressiveRubberneck = 147,
		CTaskInVehicleBasic = 150,
		CTaskCarDriveWander = 151,
		CTaskLeaveAnyCar = 152,
		CTaskComplexGetOffBoat = 153,
		CTaskCarSetTempAction = 155,
		CTaskBringVehicleToHalt = 156,
		CTaskCarDrive = 157,
		CTaskPlayerDrive = 159,
		CTaskEnterVehicle = 160,
		CTaskEnterVehicleAlign = 161,
		CTaskOpenVehicleDoorFromOutside = 162,
		CTaskEnterVehicleSeat = 163,
		CTaskCloseVehicleDoorFromInside = 164,
		CTaskInVehicleSeatShuffle = 165,
		CTaskExitVehicleSeat = 167,
		CTaskCloseVehicleDoorFromOutside = 168,
		CTaskControlVehicle = 169,
		CTaskMotionInAutomobile = 170,
		CTaskMotionInVehicle = 173,
		CTaskGetOnTrain = 178,
		CTaskGetOffTrain = 179,
		CTaskGoToCarDoorAndStandStill = 195,
		CTaskMoveGoToVehicleDoor = 196,
		CTasksArrayetPedInVehicle = 197,
		CTasksArrayetPedOutOfVehicle = 198,
		CTaskVehicleMountedWeapon = 199,
		CTaskVehicleGun = 200,
		CTaskMoveGoToPoint = 205,
		CTaskMoveAchieveHeading = 206,
		CTaskComplexGoToPointAndStandStillTimed = 208,
		CTaskMoveFollowPointRoute = 209,
		CTaskExhaustedFlee = 215,
		CTasksArraymartFlee = 218,
		CTaskFlyAway = 219,
		CTaskFollowLeaderInFormation = 223,
		CTaskGoToPointAnyMeans = 224,
		CTaskFollowLeaderAnyMeans = 226,
		CTaskFlyToPoint = 228,
		CTaskFlyingWander = 229,
		CTaskGoToPointAiming = 230,
		CTaskMoveFollowNavMesh = 238,
		CTaskMoveGoToPointOnRoute = 239,
		CTaskEscapeBlast = 240,
		CTaskMoveSlideToCoord = 252,
		CTaskGetOutOfWater = 256,
		CTaskFollowWaypointRecording = 261,
		CTaskMotionPed = 264,
		CTaskHumanLocomotion = 268,
		CTaskMotionStrafing = 270,
		CTaskMotionAiming = 272,
		CTaskBirdLocomotion = 273,
		CTaskFlightlessBirdLocomotion = 274,
		CTaskFishLocomotion = 278,
		CTaskQuadLocomotion = 279,
		CTaskMotionSwimming = 281,
		CTaskMotionAimingTransition = 285,
		CTaskCover = 287,
		CTaskMotionInCover = 288,
		CTaskAimAndThrowProjectile = 289,
		CTaskGun = 290,
		CTaskAimFromGround = 291,
		CTaskAimGunVehicleDriveBy = 295,
		CTaskAimGunScripted = 296,
		CTaskReloadGun = 298,
		CTaskEnterCover = 300,
		CTaskExitCover = 301,
		CTaskAimGunFromCoverIntro = 302,
		CTaskAimGunFromCoverOutro = 303,
		CTaskAimGunBlindFire = 304,
		CTaskCombatClosestTargetInArea = 307,
		CTaskCombatAdditionalTask = 308,
		CTaskInCover = 309,
		CTaskAimSweep = 313,
		CTaskAgitated = 320,
		CTaskAgitatedAction = 321,
		CTaskConfront = 322,
		CTaskCrouchToggle = 327,
		CTaskParachute = 334,
		CTaskCombatSeekCover = 339,
		CTaskCombatFlank = 341,
		CTaskCombat = 342,
		CTaskCombatMounted = 343,
		CTaskThreatResponse = 351,
		CTaskDraggingToSafety = 363,
		CTaskDraggedToSafety = 364,
		CTaskMoveWithinAttackWindow = 366,
		CTaskMoveWithinDefensiveArea = 367,
		CTaskBoatChase = 370,
		CTaskBoatCombat = 371,
		CTaskBoatStrafe = 372,
		CTaskAdvance = 383,
		CTaskCharge = 384,
		CTaskAnimatedHitByExplosion = 387,
		CTaskNMBrace = 391,
		CTaskNMShot = 394,
		CTaskNMHighFall = 395,
		CTaskNMExplosion = 399,
		CTaskNMDangle = 402,
		CTaskBlendFromNM = 406,
		CTaskNMControl = 407,
		CTaskNMSit = 414,
		CTaskNMSimple = 416,
		CTaskRageRagdoll = 417,
		CTaskJumpVault = 420,
		CTaskJump = 421,
		CTaskFall = 422,
		CTaskChat = 425,
		CTaskBomb = 431,
		CTaskDetonator = 432,
		CTaskAnimatedAttach = 434,
		CTaskCutScene = 440,
		CTaskDiveToGround = 443,
		CTaskReactAndFlee = 444,
		CTaskCallPolice = 446,
		CTaskVehicleDeadDriver = 465,
		CTaskVehicleStop = 468,
		CTaskVehicleCrash = 480,
		CTaskVehiclePlayerDriveAutomobile = 493,
		CTaskVehiclePlayerDriveBike = 494,
		CTaskVehiclePlayerDriveBoat = 495,
		CTaskVehiclePlayerDriveSubmarine = 496,
		CTaskVehiclePlayerDriveSubmarineCar = 497,
		CTaskVehiclePlayerDrivePlane = 498,
		CTaskVehiclePlayerDriveHeli = 499,
		CTaskVehiclePlayerDriveAutogyro = 500,
		CTaskVehiclePlayerDriveDiggerArm = 501,
		CTaskVehiclePlayerDriveTrain = 502,
		CTaskVehicleTransformToSubmarine = 527,
		CTaskAnimatedFallback = 528
	};
	enum
	{
		TASK_PRIORITY_LOWEST = 0,
		TASK_PRIORITY_LOW,
		TASK_PRIORITY_NORMAL,
		TASK_PRIORITY_HIGH,
		TASK_PRIORITY_HIGHEST,
		TASK_PRIORITY_REAL_TIME
	};
};

typedef void CTaskJumpVault;
typedef void CTaskPlayerOnFoot;
typedef void CTaskPlayerDrive;

class VTasks
{
	std::string* TasksArray[500] = { nullptr };
	VTasks();
	static VTasks *singleInstance;
public:
	static VTasks* Get()
	{
		if (!singleInstance)
			singleInstance = new VTasks();
		return singleInstance;
	}

	std::string GetTaskName(int64_t id);
	~VTasks();
	void *GetTaskFromID(unsigned int taskID);
};



