#pragma once
namespace rage {
	class CPedFactory;
	class CPedModelInfo;
	class phInstGta;
	class CEntity;
	class CBaseModelInfo;
	class CPed;
	class CDynamicEntity;
	class CPortalTracker;
	class CPhysical;
	class CPedTasks;
	class CPlayerInfo;
	class ioConstantLightEffect;
	class fwWantedLightEffect;
	class CPlayerPedTargeting;
	class CPedInventory;
	class CPedWeaponManager;
	class CVehicle;
	class CEntityDrawHandler;
	class CCustomShaderEffectBaseType;
	class fragDrawable;
	class audCarAudioEntity;
	class CWeaponInfo;
	class CVehicleIntelligence;
	class CVehicleTaskManager;
	class CTaskTree;
	class CTask;
};